#
# Copyright (C) 2003 Wolfgang Denk, DENX Software Engineering, wd@denx.de
#
# SPDX-License-Identifier: GPL-2.0
#

include $(TOPDIR)/config.mk

OBJS-y	+= start_1004k.o
OBJS-y	+= cpu.o

include $(TOPDIR)/end.mk
