#
# Copyright (C) 2000-2002 Wolfgang Denk, DENX Software Engineering, wd@denx.de
#
# SPDX-License-Identifier: GPL-2.0
#

include $(TOPDIR)/config.mk

OBJS-y	= crc32.o ctype.o display_options.o string.o vsprintf.o

include $(TOPDIR)/end.mk
