#
# Copyright (C) 2003 Wolfgang Denk, DENX Software Engineering, wd@denx.de
#
# SPDX-License-Identifier: GPL-2.0
#

include $(TOPDIR)/config.mk

OBJS-y	= board.o time.o mips_linux.o

include $(TOPDIR)/end.mk
